# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95749208ba57430c40492edb9d9c8931d309198d37de962d6cda25b3184ac04bc84c70d97145b6caffbe814039f06860df83aa4ae96bec4a2eae80536ef53d7e

test:
  secret_key_base: 2db8d6ddba9c7151ebdb175577c4a0ae150d7a4f660ba0aa28ad56f6e33493b75281dba12b8befb31d2555100d0eac37ecb8b0bb670f12691c0e325e25d242e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
